### ISSUE TITLE
Не могу соединить или импортировать самодельные .omf файлы из СДК в .omf editor

### ISSUE THREAD

**Issue by shadept-GitHub** [forward-frontier/omf_editor#2]
Вот что показывает эдитор при залитии кастомных омф файлов.
![image](https://user-images.githubusercontent.com/65095770/153086811-3f7bc02f-b6d0-4821-b9e0-425568c81456.png)
![image](https://user-images.githubusercontent.com/65095770/153086943-b9292e4e-c127-4d9f-98e6-0e2c9dcd2f05.png)
Что делать? Делаю для ЗП и использую сборку СДК от DaaGuda.

**Comment by mortany** [comment]
Было решено пользователем самостоятельно.
